version: "3.8"
services:
  mysql_database:
    container_name: mysql
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Fortaleza
  redis_server:
    container_name: redis
    image: redis:alpine
    command: redis-server
    restart: always
    ports:
      - "6379:6379"      
  app:
    image: node:16-alpine
    command: sh -c "yarn install && yarn dev"
    ports:
      - 3005:3005
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: music
      MYSQL_PORT: 3306
    depends_on:
      - mysql_database
      - redis_server
    stdin_open: true
    tty: true
